---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Notes
- type: directory
  path: _app/_posts/note
  label: Notes
  create: documents
  match: "**/*.md"
- type: directory
  path: _app/_examples/note
  label: Example Notes
  create: all
  match: "**/*"
- type: heading
  label: News
- type: directory
  path: _app/_posts/news
  label: News
  create: documents
  match: "**/*.md"
- type: directory
  path: _app/_examples/news
  label: Example Articles
  create: all
  match: "**/*"
- type: heading
  label: Pages
- type: directory
  path: _app/_pages
  label: Pages / Default
  create: documents
  match: "*md"
- type: directory
  path: _app/_pages/themes/curtana
  label: Pages / Curtana
  create: documents
  match: "*md"
- type: directory
  path: _app/_pages
  label: Pages / All
  create: all
  match: "**/*"
- type: heading
  label: Site Configuration
- type: document
  path: _app/_data/authors.yml
  label: Authors
- type: document
  path: _app/_pages/index.html
  label: Index page
- type: document
  path: _app/_data/header.yml
  label: Header
- type: document
  path: _app/_data/footer.yml
  label: Footer
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: "."
  label: Configuration files
  create: all
  match: "**/*.yml"
upload_dir: uploads
public_path: "/_site/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6-node12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
